import type { SeedJob } from './seed.types';

/**
 * Listings across the six seeded employers. Deliberately varied — every job type, every
 * work mode, a wide pay range, plus drafts and closed roles — so the filters on the jobs
 * screen have something to actually narrow.
 */
export const SEED_JOBS: readonly SeedJob[] = [
  /* ------------------------------------------------------------ Nimbus Labs */
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'Senior Backend Engineer',
      description:
        'Own our API from schema to production. You will shape the data model, keep the request path fast, and help the team make decisions that survive contact with real traffic.\n\nWe care more about how you reason through a trade-off than which framework you last used.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['TypeScript', 'Node.js', 'MongoDB', 'REST'],
      locations: ['Pune', 'Remote'],
      ctcMin: 1_800_000,
      ctcMax: 2_800_000,
      experienceMinYears: 4,
      experienceMaxYears: 8,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'Frontend Engineer, Design Systems',
      description:
        'Build the component library the rest of the product is assembled from. Accessibility and theming are first-class here, not a retrofit.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['React', 'TypeScript', 'CSS', 'Accessibility'],
      locations: ['Remote'],
      ctcMin: 1_600_000,
      ctcMax: 2_400_000,
      experienceMinYears: 3,
      experienceMaxYears: 6,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'Platform Engineer (SRE)',
      description:
        'Keep the lights on and make the on-call rota boring. Terraform, observability, and a genuine say in the architecture.',
      role: 'operations',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Kubernetes', 'Terraform', 'AWS', 'Observability'],
      locations: ['Pune'],
      ctcMin: 2_000_000,
      ctcMax: 3_200_000,
      experienceMinYears: 5,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'Engineering Intern',
      description:
        'Six months alongside the platform team. You will ship something real and have your name on it.',
      role: 'engineering',
      jobType: 'internship',
      workMode: 'onsite',
      skills: ['JavaScript', 'Git'],
      locations: ['Pune'],
      ctcMin: 300_000,
      ctcMax: 480_000,
      experienceMaxYears: 1,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: false,
    job: {
      title: 'Developer Advocate',
      description:
        'Still shaping this one — talks, docs and sample apps, with real engineering time protected.',
      role: 'marketing',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['Writing', 'Public Speaking', 'TypeScript'],
      locations: ['Remote'],
      ctcMin: 1_400_000,
      ctcMax: 2_000_000,
      experienceMinYears: 3,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'Technical Writer',
      description:
        'Our docs are the product for half our users. Own them: reference, guides, and the release notes nobody dreads reading.',
      role: 'other',
      jobType: 'contract',
      workMode: 'remote',
      skills: ['Technical Writing', 'Markdown', 'Git', 'APIs'],
      locations: ['Remote'],
      ctcMin: 1_100_000,
      ctcMax: 1_700_000,
      experienceMinYears: 2,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    close: true,
    job: {
      title: 'Staff Engineer, Developer Experience',
      description:
        'Filled in March — kept here so the archive is not empty. Build tools that make the other forty engineers faster.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['TypeScript', 'Build Systems', 'CI/CD'],
      locations: ['Pune', 'Remote'],
      ctcMin: 3_000_000,
      ctcMax: 4_500_000,
      experienceMinYears: 8,
    },
  },
  {
    hrEmail: 'grace@nimbuslabs.test',
    publish: true,
    job: {
      title: 'QA Automation Engineer',
      description:
        'Own the test pyramid. We would rather catch it in CI than in a customer’s account.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Playwright', 'TypeScript', 'CI/CD', 'Test Design'],
      locations: ['Pune'],
      ctcMin: 1_300_000,
      ctcMax: 2_000_000,
      experienceMinYears: 3,
      experienceMaxYears: 7,
    },
  },

  /* ------------------------------------------------------- Aether Analytics */
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Data Engineer',
      description:
        'Build the pipelines the forecasting team depends on. Batch today, streaming where it earns its keep.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Python', 'Airflow', 'SQL', 'Spark'],
      locations: ['Bengaluru'],
      ctcMin: 1_900_000,
      ctcMax: 3_000_000,
      experienceMinYears: 4,
      experienceMaxYears: 9,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Machine Learning Engineer',
      description:
        'Take forecasting models from a notebook to something that runs every night without anyone watching.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['Python', 'PyTorch', 'MLOps', 'SQL'],
      locations: ['Bengaluru', 'Hyderabad'],
      ctcMin: 2_400_000,
      ctcMax: 3_800_000,
      experienceMinYears: 4,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Product Designer',
      description:
        'Dense, information-heavy tooling for analysts. The craft here is making complexity legible, not hiding it.',
      role: 'design',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['Figma', 'Design Systems', 'Prototyping', 'User Research'],
      locations: ['Remote', 'Bengaluru'],
      ctcMin: 1_500_000,
      ctcMax: 2_300_000,
      experienceMinYears: 3,
      experienceMaxYears: 7,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Analytics Consultant (Contract)',
      description:
        'Six-month engagement embedded with a logistics client. Heavy SQL, heavier stakeholder management.',
      role: 'other',
      jobType: 'contract',
      workMode: 'hybrid',
      skills: ['SQL', 'Tableau', 'Stakeholder Management'],
      locations: ['Bengaluru'],
      ctcMin: 1_400_000,
      ctcMax: 2_200_000,
      experienceMinYears: 3,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Analytics Engineer',
      description:
        'Sit between the warehouse and the dashboards. dbt models, tests, and documentation people trust.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['dbt', 'SQL', 'Snowflake', 'Python'],
      locations: ['Remote', 'Hyderabad'],
      ctcMin: 1_700_000,
      ctcMax: 2_600_000,
      experienceMinYears: 3,
      experienceMaxYears: 8,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: true,
    job: {
      title: 'Data Science Intern',
      description:
        'A summer on the forecasting team. Bring curiosity and a willingness to have your model questioned.',
      role: 'engineering',
      jobType: 'internship',
      workMode: 'onsite',
      skills: ['Python', 'Statistics', 'pandas'],
      locations: ['Bengaluru'],
      ctcMin: 360_000,
      ctcMax: 600_000,
      experienceMaxYears: 1,
    },
  },
  {
    hrEmail: 'raj@aetheranalytics.test',
    publish: false,
    job: {
      title: 'Head of Data Platform',
      description: 'Draft — still deciding whether this is one role or two.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Leadership', 'Data Architecture', 'Cloud'],
      locations: ['Bengaluru'],
      ctcMin: 4_000_000,
      ctcMax: 6_000_000,
      experienceMinYears: 10,
    },
  },

  /* -------------------------------------------------------- Northwind Retail */
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Full Stack Engineer',
      description:
        'Storefront and the tools behind it. You will see your work in a shop the same week you ship it.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['React', 'Node.js', 'PostgreSQL'],
      locations: ['Mumbai'],
      ctcMin: 1_400_000,
      ctcMax: 2_200_000,
      experienceMinYears: 2,
      experienceMaxYears: 6,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Product Manager, Storefront',
      description:
        'Own the buying journey end to end, from search to the confirmation screen. You will have real traffic to learn from.',
      role: 'product',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Roadmapping', 'Analytics', 'Stakeholder Management'],
      locations: ['Mumbai', 'Pune'],
      ctcMin: 2_200_000,
      ctcMax: 3_400_000,
      experienceMinYears: 5,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Retail Operations Analyst',
      description:
        'Stock, staffing and store performance. Spreadsheets to start, better systems if you can argue for them.',
      role: 'operations',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['Excel', 'SQL', 'Forecasting'],
      locations: ['Mumbai'],
      ctcMin: 900_000,
      ctcMax: 1_500_000,
      experienceMinYears: 2,
      experienceMaxYears: 5,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Brand Designer (Part time)',
      description:
        'Campaign artwork across print and digital, three days a week, working directly with the marketing lead.',
      role: 'design',
      jobType: 'part_time',
      workMode: 'remote',
      skills: ['Illustrator', 'Branding', 'Typography'],
      locations: ['Remote'],
      ctcMin: 600_000,
      ctcMax: 1_000_000,
      experienceMinYears: 2,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: false,
    job: {
      title: 'Finance Analyst',
      description: 'Draft listing — headcount not yet approved.',
      role: 'finance',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['Excel', 'Financial Modelling'],
      locations: ['Mumbai'],
      ctcMin: 1_000_000,
      ctcMax: 1_600_000,
      experienceMinYears: 2,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Store Systems Engineer',
      description:
        'The point-of-sale estate across 200 shops. Unglamorous, extremely load-bearing, and never boring.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['Java', 'Linux', 'Networking', 'PostgreSQL'],
      locations: ['Mumbai', 'Pune'],
      ctcMin: 1_500_000,
      ctcMax: 2_300_000,
      experienceMinYears: 4,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Customer Support Lead',
      description:
        'Build the team and the playbook. You will be the loudest voice for the customer in product review.',
      role: 'operations',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Team Leadership', 'Zendesk', 'Process Design'],
      locations: ['Mumbai'],
      ctcMin: 1_200_000,
      ctcMax: 1_900_000,
      experienceMinYears: 4,
    },
  },
  {
    hrEmail: 'sofia@northwindretail.test',
    publish: true,
    job: {
      title: 'Visual Merchandiser (Freelance)',
      description:
        'Seasonal window and in-store layouts across the western region. Project by project.',
      role: 'design',
      jobType: 'freelance',
      workMode: 'onsite',
      skills: ['Merchandising', 'Styling', 'Retail'],
      locations: ['Mumbai', 'Pune'],
      ctcMin: 500_000,
      ctcMax: 900_000,
      experienceMinYears: 1,
    },
  },

  /* ----------------------------------------------------------- Vertex Health */
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'Senior Software Engineer, Clinical Systems',
      description:
        'Scheduling and records for hospital networks. Regulated software: audited, versioned, and reviewed by people whose job is to find the gap.\n\nIf you like problems where correctness matters more than velocity, this is one.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Java', 'Spring', 'PostgreSQL', 'HL7'],
      locations: ['Chennai', 'Bengaluru'],
      ctcMin: 2_100_000,
      ctcMax: 3_300_000,
      experienceMinYears: 5,
      experienceMaxYears: 10,
    },
  },
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'Security Engineer',
      description:
        'Patient data, so the threat model is not hypothetical. Threat modelling, reviews, and the unglamorous work of fixing what you find.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['AppSec', 'Threat Modelling', 'Cryptography', 'Cloud Security'],
      locations: ['Remote', 'Chennai'],
      ctcMin: 2_300_000,
      ctcMax: 3_600_000,
      experienceMinYears: 5,
    },
  },
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'UX Researcher',
      description:
        'Spend real time in wards and clinics. The people using this are busy, tired, and cannot afford a confusing screen.',
      role: 'design',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['User Research', 'Interviewing', 'Usability Testing', 'Synthesis'],
      locations: ['Chennai'],
      ctcMin: 1_400_000,
      ctcMax: 2_200_000,
      experienceMinYears: 3,
    },
  },
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'Mobile Engineer (React Native)',
      description:
        'The clinician-facing app: rounds, notes and alerts, on devices that live in a pocket for twelve hours.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['React Native', 'TypeScript', 'Offline Sync'],
      locations: ['Chennai', 'Remote'],
      ctcMin: 1_700_000,
      ctcMax: 2_700_000,
      experienceMinYears: 3,
      experienceMaxYears: 8,
    },
  },
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'Compliance Manager',
      description:
        'Own the audit calendar and the evidence behind it. You will work with engineering rather than at them.',
      role: 'operations',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['ISO 27001', 'Audit', 'Policy', 'Risk'],
      locations: ['Chennai'],
      ctcMin: 1_600_000,
      ctcMax: 2_400_000,
      experienceMinYears: 6,
    },
  },
  {
    hrEmail: 'priya@vertexhealth.test',
    publish: true,
    job: {
      title: 'Technical Recruiter',
      description:
        'Hire the engineers who build all of the above. Small team, high standards, no spray-and-pray sourcing.',
      role: 'hr',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Sourcing', 'Interviewing', 'Employer Branding'],
      locations: ['Chennai', 'Remote'],
      ctcMin: 1_000_000,
      ctcMax: 1_700_000,
      experienceMinYears: 3,
    },
  },

  /* ----------------------------------------------------------- Orbit Fintech */
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    job: {
      title: 'Payments Engineer',
      description:
        'Ledgers, reconciliation and settlement. Money must not be created or destroyed by a race condition, and here it will not be.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Go', 'PostgreSQL', 'Distributed Systems', 'Payments'],
      locations: ['Gurugram', 'Bengaluru'],
      ctcMin: 2_500_000,
      ctcMax: 4_000_000,
      experienceMinYears: 5,
      experienceMaxYears: 12,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    job: {
      title: 'Risk Analyst',
      description:
        'Underwriting models for small-business lending. Half statistics, half judgement about the half you cannot measure.',
      role: 'finance',
      jobType: 'full_time',
      workMode: 'onsite',
      skills: ['Python', 'Statistics', 'Credit Risk', 'SQL'],
      locations: ['Gurugram'],
      ctcMin: 1_800_000,
      ctcMax: 2_800_000,
      experienceMinYears: 3,
      experienceMaxYears: 8,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    job: {
      title: 'Enterprise Sales Manager',
      description:
        'Long cycles, technical buyers, and a product that genuinely works. Bring patience and a good CRM habit.',
      role: 'sales',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Enterprise Sales', 'Negotiation', 'CRM'],
      locations: ['Gurugram', 'Bengaluru'],
      ctcMin: 2_000_000,
      ctcMax: 3_500_000,
      experienceMinYears: 5,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    job: {
      title: 'Backend Engineer, Lending',
      description:
        'The origination flow, from application to disbursal. Plenty of state, all of it consequential.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Event Sourcing'],
      locations: ['Remote', 'Gurugram'],
      ctcMin: 1_900_000,
      ctcMax: 3_000_000,
      experienceMinYears: 3,
      experienceMaxYears: 9,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    job: {
      title: 'Growth Marketer',
      description:
        'Own acquisition for the self-serve product. Experiments, not vibes — you will have the analytics to prove it either way.',
      role: 'marketing',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['SEO', 'Paid Acquisition', 'Analytics', 'Copywriting'],
      locations: ['Remote'],
      ctcMin: 1_300_000,
      ctcMax: 2_100_000,
      experienceMinYears: 3,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: false,
    job: {
      title: 'Engineering Manager, Payments',
      description: 'Draft — waiting on the team split before this goes live.',
      role: 'engineering',
      jobType: 'full_time',
      workMode: 'hybrid',
      skills: ['Leadership', 'Distributed Systems', 'Coaching'],
      locations: ['Gurugram'],
      ctcMin: 3_500_000,
      ctcMax: 5_000_000,
      experienceMinYears: 9,
    },
  },
  {
    hrEmail: 'daniel@orbitfintech.test',
    publish: true,
    close: true,
    job: {
      title: 'Data Protection Officer',
      description: 'Closed — we hired internally. Kept for the record.',
      role: 'operations',
      jobType: 'part_time',
      workMode: 'remote',
      skills: ['Privacy', 'GDPR', 'Policy'],
      locations: ['Remote'],
      ctcMin: 900_000,
      ctcMax: 1_400_000,
      experienceMinYears: 5,
    },
  },

  /* ----------------------------------------------------------- Lumen Studios */
  {
    hrEmail: 'anika@lumenstudios.test',
    publish: true,
    job: {
      title: 'Senior Product Designer',
      description:
        'Client work across three or four products a year. You will own the whole arc — research, interface, and the handover that makes it survive.',
      role: 'design',
      jobType: 'full_time',
      workMode: 'remote',
      skills: ['Figma', 'Interaction Design', 'Design Systems', 'Prototyping'],
      locations: ['Remote', 'Goa'],
      ctcMin: 1_800_000,
      ctcMax: 2_800_000,
      experienceMinYears: 5,
    },
  },
  {
    hrEmail: 'anika@lumenstudios.test',
    publish: true,
    job: {
      title: 'Motion Designer (Freelance)',
      description:
        'Product launch films and interface motion. Project rates, remote, roughly one engagement a month.',
      role: 'design',
      jobType: 'freelance',
      workMode: 'remote',
      skills: ['After Effects', 'Motion Design', 'Storyboarding'],
      locations: ['Remote'],
      ctcMin: 700_000,
      ctcMax: 1_400_000,
      experienceMinYears: 2,
    },
  },
  {
    hrEmail: 'anika@lumenstudios.test',
    publish: true,
    job: {
      title: 'Frontend Engineer (Contract)',
      description:
        'Turn our design work into the real thing. Six months, with a strong chance of the next project after it.',
      role: 'engineering',
      jobType: 'contract',
      workMode: 'remote',
      skills: ['React', 'TypeScript', 'CSS', 'Animation'],
      locations: ['Remote'],
      ctcMin: 1_500_000,
      ctcMax: 2_200_000,
      experienceMinYears: 3,
    },
  },
  {
    hrEmail: 'anika@lumenstudios.test',
    publish: true,
    job: {
      title: 'Design Intern',
      description:
        'Three months in the studio in Goa. Real client work, reviewed properly, with your name in the credits.',
      role: 'design',
      jobType: 'internship',
      workMode: 'onsite',
      skills: ['Figma', 'Typography'],
      locations: ['Goa'],
      ctcMin: 240_000,
      ctcMax: 420_000,
      experienceMaxYears: 1,
    },
  },
  {
    hrEmail: 'anika@lumenstudios.test',
    publish: true,
    job: {
      title: 'Studio Operations Manager',
      description:
        'Scheduling, budgets and the thousand small things that keep a studio from running on adrenaline.',
      role: 'operations',
      jobType: 'part_time',
      workMode: 'hybrid',
      skills: ['Project Management', 'Budgeting', 'Scheduling'],
      locations: ['Goa'],
      ctcMin: 700_000,
      ctcMax: 1_200_000,
      experienceMinYears: 3,
    },
  },
];
